"""add test run import foundation

Revision ID: 00e1ba1b6d7a
Revises: a3aa904e1fc9
Create Date: 2026-07-12 02:43:02.238114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e1ba1b6d7a'
down_revision = 'a3aa904e1fc9'
branch_labels = None
depends_on = None


def set_sqlite_foreign_keys(enabled):
    connection = op.get_bind()
    if connection.dialect.name != 'sqlite':
        return

    value = 'ON' if enabled else 'OFF'
    with op.get_context().autocommit_block():
        connection.exec_driver_sql(f'PRAGMA foreign_keys={value}')


def check_sqlite_foreign_keys():
    connection = op.get_bind()
    if connection.dialect.name != 'sqlite':
        return

    violations = connection.exec_driver_sql('PRAGMA foreign_key_check').fetchall()
    if violations:
        raise RuntimeError(f'Foreign key violations after migration: {violations}')


def upgrade():
    set_sqlite_foreign_keys(False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('runner', sa.String(length=80), nullable=True),
    sa.Column('environment', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'source_type', 'report_hash', name='uq_test_run_version_source_hash')
    )
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_run_version_id'), ['version_id'], unique=False)

    with op.batch_alter_table('test_execution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_run_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('external_case_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.create_index(batch_op.f('ix_test_execution_test_run_id'), ['test_run_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_test_execution_test_run_id_test_run',
            'test_run',
            ['test_run_id'],
            ['id'],
        )

    set_sqlite_foreign_keys(True)
    check_sqlite_foreign_keys()

    # ### end Alembic commands ###


def downgrade():
    set_sqlite_foreign_keys(False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_execution', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_test_execution_test_run_id_test_run',
            type_='foreignkey',
        )
        batch_op.drop_index(batch_op.f('ix_test_execution_test_run_id'))
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('external_case_key')
        batch_op.drop_column('test_run_id')

    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_version_id'))

    op.drop_table('test_run')
    set_sqlite_foreign_keys(True)
    check_sqlite_foreign_keys()
    # ### end Alembic commands ###
