"""enforce test run external case key uniqueness

Revision ID: 02e4b0712fc4
Revises: 00e1ba1b6d7a
Create Date: 2026-07-12 12:48:41.615502

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '02e4b0712fc4'
down_revision = '00e1ba1b6d7a'
branch_labels = None
depends_on = None


def set_sqlite_foreign_keys(enabled):
    connection = op.get_bind()
    if connection.dialect.name != 'sqlite':
        return

    value = 'ON' if enabled else 'OFF'
    with op.get_context().autocommit_block():
        connection.exec_driver_sql(f'PRAGMA foreign_keys={value}')


def check_sqlite_foreign_keys():
    connection = op.get_bind()
    if connection.dialect.name != 'sqlite':
        return

    violations = connection.exec_driver_sql('PRAGMA foreign_key_check').fetchall()
    if violations:
        raise RuntimeError(f'Foreign key violations after migration: {violations}')


def upgrade():
    set_sqlite_foreign_keys(False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_execution', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_test_execution_run_external_key', ['test_run_id', 'external_case_key'])

    set_sqlite_foreign_keys(True)
    check_sqlite_foreign_keys()

    # ### end Alembic commands ###


def downgrade():
    set_sqlite_foreign_keys(False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_execution', schema=None) as batch_op:
        batch_op.drop_constraint('uq_test_execution_run_external_key', type_='unique')

    set_sqlite_foreign_keys(True)
    check_sqlite_foreign_keys()
    # ### end Alembic commands ###
