"""add test case crud fields

Revision ID: 8ca595558401
Revises: a66931a06a60
Create Date: 2026-07-09 23:50:27.537571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca595558401'
down_revision = 'a66931a06a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    op.execute(
        """
        UPDATE test_case
        SET version_id = (
            SELECT MIN(version.id)
            FROM version
            WHERE version.project_id = test_case.project_id
        )
        WHERE version_id IS NULL
        """
    )
    op.execute("UPDATE test_case SET code = 'MOCK-TESTCASE-' || id WHERE code IS NULL OR code = ''")
    op.execute("UPDATE test_case SET status = 'active' WHERE status IS NULL OR status = ''")

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.alter_column('version_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('code', existing_type=sa.String(length=80), nullable=False)
        batch_op.create_unique_constraint('uq_test_case_version_code', ['version_id', 'code'])
        batch_op.create_foreign_key('fk_test_case_version_id_version', 'version', ['version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_case_version_id_version', type_='foreignkey')
        batch_op.drop_constraint('uq_test_case_version_code', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('code')
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
