"""add version crud fields

Revision ID: a66931a06a60
Revises: 6a6ef4fd5a4e
Create Date: 2026-07-05 23:43:25.065901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66931a06a60'
down_revision = '6a6ef4fd5a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    op.execute("UPDATE version SET code = 'MOCK-VERSION-' || id WHERE code IS NULL OR code = ''")

    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.alter_column('code', existing_type=sa.String(length=80), nullable=False)
        batch_op.create_unique_constraint('uq_version_project_code', ['project_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_constraint('uq_version_project_code', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('description')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
